Repository phpDocumentor/guides, pull requests merged in 2024-04, with the labels that each got.

#974 Backport on closed merge requests only
  .github/workflows/backport.yaml
Labels: auto-backport-to-1.x

#976 Move check to job level
  .github/workflows/backport.yaml
Labels: auto-backport-to-1.x

#973 [TASK] Add test to prove proper error handling for plantuml
  tests/Integration/tests/graphs/plantuml-server-error/expected/index.html
  tests/Integration/tests/graphs/plantuml-server-error/expected/logs/warning.log
  tests/Integration/tests/graphs/plantuml-server-error/input/Plantuml/something.plantuml
  tests/Integration/tests/graphs/plantuml-server-error/input/guides.xml
  tests/Integration/tests/graphs/plantuml-server-error/input/index.rst
Labels: auto-backport-to-1.x

#978 [FIX] catch transport exception when host can not be reached
  packages/guides-graphs/src/Graphs/Renderer/PlantumlServerRenderer.php
  packages/guides-restructured-text/tests/unit/Parser/Productions/RuleTestCase.php
  packages/guides-restructured-text/tests/unit/Parser/Productions/SectionRuleTest.php
  tests/Integration/tests/graphs/plantuml-server-error/expected/logs/warning.log
  tests/Integration/tests/graphs/plantuml-server-error/input/guides.xml
Labels: auto-backport-to-1.x

#972 Extendable compiler context
  composer.json
  composer.lock
  packages/guides/composer.json
  packages/guides/src/Compiler/CompilerContext.php
  packages/guides/src/Compiler/CompilerContextInterface.php
  packages/guides/src/Compiler/NodeTransformers/CitationInlineNodeTransformer.php
  packages/guides/src/Compiler/NodeTransformers/CitationTargetTransformer.php
  packages/guides/src/Compiler/NodeTransformers/ClassNodeTransformer.php
  packages/guides/src/Compiler/NodeTransformers/CollectLinkTargetsTransformer.php
  packages/guides/src/Compiler/NodeTransformers/DocumentBlockNodeTransformer.php
  packages/guides/src/Compiler/NodeTransformers/DocumentEntryRegistrationTransformer.php
  packages/guides/src/Compiler/NodeTransformers/FootNodeNamedTransformer.php
  packages/guides/src/Compiler/NodeTransformers/FootNodeNumberedTransformer.php
  packages/guides/src/Compiler/NodeTransformers/FootnoteInlineNodeTransformer.php
  packages/guides/src/Compiler/NodeTransformers/ListNodeTransformer.php
  packages/guides/src/Compiler/NodeTransformers/MenuNodeTransformers/AbstractMenuEntryNodeTransformer.php
  packages/guides/src/Compiler/NodeTransformers/MenuNodeTransformers/ContentsMenuEntryNodeTransformer.php
  packages/guides/src/Compiler/NodeTransformers/MenuNodeTransformers/ExternalMenuEntryNodeTransformer.php
  packages/guides/src/Compiler/NodeTransformers/MenuNodeTransformers/GlobMenuEntryNodeTransformer.php
  packages/guides/src/Compiler/NodeTransformers/MenuNodeTransformers/InternalMenuEntryNodeTransformer.php
  packages/guides/src/Compiler/NodeTransformers/MenuNodeTransformers/MenuEntryManagement.php
  packages/guides/src/Compiler/NodeTransformers/MenuNodeTransformers/SubInternalMenuEntryNodeTransformer.php
  packages/guides/src/Compiler/NodeTransformers/MenuNodeTransformers/TocNodeTransformer.php
  packages/guides/src/Compiler/NodeTransformers/MoveAnchorTransformer.php
  packages/guides/src/Compiler/NodeTransformers/SectionCreationTransformer.php
  packages/guides/src/Compiler/NodeTransformers/SectionEntryRegistrationTransformer.php
  packages/guides/src/Compiler/NodeTransformers/VariableInlineNodeTransformer.php
  packages/guides/src/Compiler/Passes/GlobalMenuPass.php
  packages/guides/src/Compiler/Passes/ImplicitHyperlinkTargetPass.php
  packages/guides/src/Compiler/Passes/ToctreeValidationPass.php
  packages/guides/tests/unit/Compiler/CompilerContextTest.php
  phpstan-baseline.neon
  psalm-baseline.xml
Labels: auto-backport-to-1.x, deprecation

#980 Backport/972
  composer.json
  composer.lock
  packages/guides/composer.json
  packages/guides/src/Compiler/CompilerContext.php
  packages/guides/src/Compiler/CompilerContextInterface.php
  packages/guides/src/Compiler/NodeTransformers/CitationInlineNodeTransformer.php
  packages/guides/src/Compiler/NodeTransformers/CitationTargetTransformer.php
  packages/guides/src/Compiler/NodeTransformers/ClassNodeTransformer.php
  packages/guides/src/Compiler/NodeTransformers/CollectLinkTargetsTransformer.php
  packages/guides/src/Compiler/NodeTransformers/DocumentBlockNodeTransformer.php
  packages/guides/src/Compiler/NodeTransformers/DocumentEntryRegistrationTransformer.php
  packages/guides/src/Compiler/NodeTransformers/FootNodeNamedTransformer.php
  packages/guides/src/Compiler/NodeTransformers/FootNodeNumberedTransformer.php
  packages/guides/src/Compiler/NodeTransformers/FootnoteInlineNodeTransformer.php
  packages/guides/src/Compiler/NodeTransformers/ListNodeTransformer.php
  packages/guides/src/Compiler/NodeTransformers/MenuNodeTransformers/AbstractMenuEntryNodeTransformer.php
  packages/guides/src/Compiler/NodeTransformers/MenuNodeTransformers/ContentsMenuEntryNodeTransformer.php
  packages/guides/src/Compiler/NodeTransformers/MenuNodeTransformers/ExternalMenuEntryNodeTransformer.php
  packages/guides/src/Compiler/NodeTransformers/MenuNodeTransformers/GlobMenuEntryNodeTransformer.php
  packages/guides/src/Compiler/NodeTransformers/MenuNodeTransformers/InternalMenuEntryNodeTransformer.php
  packages/guides/src/Compiler/NodeTransformers/MenuNodeTransformers/MenuEntryManagement.php
  packages/guides/src/Compiler/NodeTransformers/MenuNodeTransformers/SubInternalMenuEntryNodeTransformer.php
  packages/guides/src/Compiler/NodeTransformers/MenuNodeTransformers/TocNodeTransformer.php
  packages/guides/src/Compiler/NodeTransformers/MoveAnchorTransformer.php
  packages/guides/src/Compiler/NodeTransformers/SectionCreationTransformer.php
  packages/guides/src/Compiler/NodeTransformers/SectionEntryRegistrationTransformer.php
  packages/guides/src/Compiler/NodeTransformers/VariableInlineNodeTransformer.php
  packages/guides/src/Compiler/Passes/GlobalMenuPass.php
  packages/guides/src/Compiler/Passes/ImplicitHyperlinkTargetPass.php
  packages/guides/src/Compiler/Passes/ToctreeValidationPass.php
  packages/guides/tests/unit/Compiler/CompilerContextTest.php
  phpstan-baseline.neon
  psalm-baseline.xml
Labels: backport

#988 [BUGFIX] Warn when a directive has not title
  packages/guides-restructured-text/src/RestructuredText/Directives/ConfvalDirective.php
  tests/Integration/tests/confval/confval-no-title/expected/index.html
  tests/Integration/tests/confval/confval-no-title/expected/logs/warning.log
  tests/Integration/tests/confval/confval-no-title/input/index.rst
  tests/Integration/tests/graphs/plantuml-server-error/expected/index.html
Labels: auto-backport-to-1.x

#990 [BUGFIX] Solve Deprecations in unit tests
  packages/guides-restructured-text/tests/unit/Parser/Productions/AnnotationRuleTest.php
  packages/guides-restructured-text/tests/unit/Parser/Productions/ParagraphRuleTest.php
  packages/guides-restructured-text/tests/unit/TextRoles/ReferenceTextRoleTest.php
Labels: auto-backport-to-1.x

#993 [FEATURE] Introduce directives for bootstrap cards
  packages/guides-theme-bootstrap/resources/config/guides-theme-bootstrap.php
  packages/guides-theme-bootstrap/resources/template/body/directive/card-grid.html.twig
  packages/guides-theme-bootstrap/resources/template/body/directive/card-group.html.twig
  packages/guides-theme-bootstrap/resources/template/body/directive/card.html.twig
  packages/guides-theme-bootstrap/resources/template/body/directive/card/card-image.html.twig
  packages/guides-theme-bootstrap/src/Bootstrap/Directives/CardDirective.php
  packages/guides-theme-bootstrap/src/Bootstrap/Directives/CardFooterDirective.php
  packages/guides-theme-bootstrap/src/Bootstrap/Directives/CardGridDirective.php
  packages/guides-theme-bootstrap/src/Bootstrap/Directives/CardGroupDirective.php
  packages/guides-theme-bootstrap/src/Bootstrap/Directives/CardHeaderDirective.php
  packages/guides-theme-bootstrap/src/Bootstrap/Directives/CardImageDirective.php
  packages/guides-theme-bootstrap/src/Bootstrap/Nodes/Card/CardFooterNode.php
  packages/guides-theme-bootstrap/src/Bootstrap/Nodes/Card/CardHeaderNode.php
  packages/guides-theme-bootstrap/src/Bootstrap/Nodes/Card/CardImageNode.php
  packages/guides-theme-bootstrap/src/Bootstrap/Nodes/CardGridNode.php
  packages/guides-theme-bootstrap/src/Bootstrap/Nodes/CardGroupNode.php
  packages/guides-theme-bootstrap/src/Bootstrap/Nodes/CardNode.php
  packages/guides/resources/template/html/structure/header-title.html.twig
  tests/Integration/tests/bootstrap/bootstrap-card-grid/expected/index.html
  tests/Integration/tests/bootstrap/bootstrap-card-grid/input/guides.xml
  tests/Integration/tests/bootstrap/bootstrap-card-grid/input/hero-illustration.svg
  tests/Integration/tests/bootstrap/bootstrap-card-grid/input/index.rst
  tests/Integration/tests/bootstrap/bootstrap-card-group/expected/index.html
  tests/Integration/tests/bootstrap/bootstrap-card-group/input/guides.xml
  tests/Integration/tests/bootstrap/bootstrap-card-group/input/hero-illustration.svg
  tests/Integration/tests/bootstrap/bootstrap-card-group/input/index.rst
  tests/Integration/tests/bootstrap/bootstrap-cards/expected/index.html
  tests/Integration/tests/bootstrap/bootstrap-cards/input/guides.xml
  tests/Integration/tests/bootstrap/bootstrap-cards/input/hero-illustration.svg
  tests/Integration/tests/bootstrap/bootstrap-cards/input/index.rst
Labels: auto-backport-to-1.x

#999 [BUGFIX] Display value of card-footer,
  packages/guides-theme-bootstrap/src/Bootstrap/Directives/CardFooterDirective.php
  packages/guides/resources/template/html/inline/link.html.twig
  tests/Integration/tests/bootstrap/bootstrap-card-group/expected/index.html
  tests/Integration/tests/bootstrap/bootstrap-card-group/input/index.rst
  tests/Integration/tests/bootstrap/bootstrap-cards/expected/index.html
Labels: auto-backport-to-1.x

#1001 [TASK] Add getter for Documents to RenderContext
  packages/guides/src/RenderContext.php
Labels: auto-backport-to-1.x

#1007 [TASK] Warn about duplicate anchors
  packages/guides/src/Compiler/NodeTransformers/CollectLinkTargetsTransformer.php
  packages/guides/src/Exception/DuplicateLinkAnchorException.php
  packages/guides/src/Nodes/ProjectNode.php
  tests/Integration/tests/anchor/anchor-duplicate-warning/expected/index.html
  tests/Integration/tests/anchor/anchor-duplicate-warning/expected/logs/warning.log
  tests/Integration/tests/anchor/anchor-duplicate-warning/input/index.rst
  tests/Integration/tests/anchor/anchor-duplicate-warning/input/page.rst
Labels: auto-backport-to-1.x
